### ISSUE TITLE
Cyanoseq database in Qiime2

### ISSUE THREAD

**Issue by Listen-Lii** [flefler/CyanoSeq#3]
Thank you for developing the Cyanoseq database, which is very helpful for aquatic microbial research. I want to use Cyanoseq database on my 16S rRNA gene amplicon sequencing data. I downloaded CyanoSeq_1.2_SILVA138.1_QIIME2_classifier.qza and found  it is a trained database. So, I run these codes in Qiime2: 

qiime feature-classifier classify-sklearn \
   --i-reads zotus.fa.qza \
   --i-classifier CyanoSeq_1.2_SILVA138.1_QIIME2_classifier.qza \
   --o-classification taxonomy.qza
But there is an error: Plugin error from feature-classifier: 0.

Here are messages in debug log file:

Traceback (most recent call last):
  File "/share/soft/miniconda3/envs/qiime2202208/lib/python3.8/site-packages/q2cli/commands.py", line 339, in __call__
    results = action(**arguments)
  File "<decorator-gen-428>", line 2, in classify_sklearn
  File "/share/soft/miniconda3/envs/qiime2202208/lib/python3.8/site-packages/qiime2/sdk/action.py", line 223, in bound_callable
    callable_args[name] = artifact._view(
  File "/share/soft/miniconda3/envs/qiime2202208/lib/python3.8/site-packages/qiime2/sdk/result.py", line 373, in _view
    result = transformation(self._archiver.data_dir)
  File "/share/soft/miniconda3/envs/qiime2202208/lib/python3.8/site-packages/qiime2/core/transform.py", line 70, in transformation
    new_view = transformer(view)
  File "/share/soft/miniconda3/envs/qiime2202208/lib/python3.8/site-packages/q2_feature_classifier/_taxonomic_classifier.py", line 72, in _1
    pipeline = joblib.load(os.path.join(dirname, 'sklearn_pipeline.pkl'))
  File "/share/soft/miniconda3/envs/qiime2202208/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/share/soft/miniconda3/envs/qiime2202208/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "/share/soft/miniconda3/envs/qiime2202208/lib/python3.8/pickle.py", line 1212, in load
    dispatch[key[0]](self)
KeyError: 0

Qiime2 works well when using other reference database with the same data. So, I think there may be some problems with the file CyanoSeq_1.2_SILVA138.1_QIIME2_classifier.qza. Can you fix this?

Thank you very much for your reply and suggestions.

**Comment by Apatzingan1** [comment]
Maybe the compatibility whit the Qiime version, actually working in qiime2-2023.5 and it runs smoothly

**Comment by Listen-Lii** [comment]
Thank you very much, I download qiime2-2023.5 and now it works!
